name: Build And Push

on:
  push:
    branches:    
      - main
  workflow_dispatch: 

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |-
          docker build \
            -t "ghcr.io/${{ github.repository }}:latest" \
            -t "ghcr.io/${{ github.repository }}:main" \
            -f Dockerfile .
      - name: Push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.actor }} --password-stdin ghcr.io
          docker push ghcr.io/${{ github.repository }} --all-tags